### ISSUE TITLE
Please document the pagefile resource

### ISSUE THREAD

**Issue by axos88** [SimpleFinance/chef-windows#1]
What is automatic_managed and system_managed?

**Comment by jdinthe** [comment]
Hey @axos88, we probably need to retire this repo. There was an incident a couple years back where IIRC the Windows cookbook caused the Chef 11 server depsolver to break. We forked and uploaded our own version of the cookbook in order to circumvent the problem. We no longer use this cookbook; I'd recommend checking out the [official Windows cookbook](https://github.com/chef-cookbooks/windows) instead.

Thanks!

**Comment by axos88** [comment]
yeah, i figured this out in the meantime as well :)
